AllCops:
  Excludes:
    - '*/examples/**'
    - '*/features/**'


AccessControl:
  Enabled: false

# This is disabled because some demos use UTF-8
AsciiComments:
  Enabled: false

CaseIndentation:
  Enabled: false

ClassLength:
  Max: 200
  CountComments: false  

ConstantName:  
  Enabled: false
  
DefWithParentheses:  
  Enabled: false
  
Documentation:
  Enabled: false
  
EmptyLines:
  Enabled: false

Encoding:
  Enabled: false
  
IndentationWidth :
  Enabled: false
  
# Avoid methods longer than 50 lines of code
MethodLength:
  Max: 50
  CountComments: false

NumericLiterals:
  Enabled: false
  
RaiseArgs:
  Enabled: false
  
RedundantReturn:
  Enabled: false

SpaceInsideBrackets:
  Enabled: false

TrailingWhitespace:
  Enabled: false
  
