AllCops:
  Excludes:
    - '*/examples/**'
    - '*/spec/**'


AccessControl:
  Enabled: false

# This is disabled because some demos use UTF-8
AsciiComments:
  Enabled: false

CaseIndentation:
  Enabled: false

ConstantName:  
  Enabled: false
  
DefWithParentheses:  
  Enabled: false
  
EmptyLines:
  Enabled: false

Encoding:
  Enabled: false
  
# Avoid methods longer than 30 lines of code
MethodLength:
  Max: 30
  
RedundantReturn:
  Enabled: false

SpaceInsideBrackets:
  Enabled: false

TrailingWhitespace:
  Enabled: false
  
