# This is disabled because some demos use UTF-8
AsciiComments:
  Enabled: false

CaseIndentation:
  Enabled: false

DefWithParentheses:  
  Enabled: false
  
EmptyLines:
  Enabled: false
  
# Avoid methods longer than 40 lines of code
MethodLength:
  Max: 40

SpaceInsideBrackets:
  Enabled: false
  
StringLiterals:
  Enabled: false

TrailingWhitespace:
  Enabled: false