language: ruby
rvm:
  - ruby-head
  - 2.2.2
  - 2.2.0
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-head
  - jruby-19mode


# Workaround issue of jruby-head configuration on Travis CI
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head

gemfile:
  - Gemfile
  
# whitelist
branches:  
  only:
    - master