language: ruby
dist: trusty

before_install:
  - gem update --system
  - gem install bundler  

script:
  - bundle exec rake
  
rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - ruby-head
  - jruby-9.1.9.0
  - jruby-head
  
matrix:
  allow_failures:
    - rvm: 2.6.0
    - rvm: ruby-head
    - rvm: jruby-head


# whitelist
branches:
  only:
    - master