language: ruby
rvm:
  - ruby-head
  - jruby-head  
  - 2.3.3
  - 2.2.6
  - 2.1.9
  - 2.0.0  
  - jruby    

# Workaround issue of jruby-head configuration on Travis CI
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

gemfile:
  - Gemfile
  
# whitelist
branches:  
  only:
    - master